services:
  patient-web:
    restart: always
    init: true
    build:
      context: .
    environment:
      - ROOT_URL=${ROOT_URL}
      - PORT=${PORT}
      - MONGO_URL=${MONGO_URL}
      - HTTP_FORWARDED_COUNT=${HTTP_FORWARDED_COUNT}
    depends_on:
      patient-db:
        condition: service_healthy
    networks:
      - patient-network
    ports:
      - "${PORT}:${PORT}"

  patient-db:
    restart: always
    extends:
      file: storage.yaml
      service: database
    volumes:
      - "patient-data:${MONGO_DB_PATH}"
    networks:
      - patient-network

networks:
  patient-network:

volumes:
  patient-data:
