name: is-healthy
description: >
  Checks if a given container is healthy.

inputs:

  container:
    required: true

  timeout:
    required: true
    default: 30

  polling-interval:
    required: true
    default: 1

  debug:
    type: boolean
    default: false


runs:

  using: composite

  steps:

    - name: Wait for container to be healthy

      env:
        NAME_OR_ID: ${{ inputs.container }}
        TIMEOUT: ${{ inputs.timeout }}
        POLLING_INTERVAL: ${{ inputs.polling-interval }}

      shell: bash

      run: |
        timeout "${TIMEOUT}" bash -c \
         'until docker inspect --format "{{json .State.Health}}" "${NAME_OR_ID}" | jq -e ".Status == \"healthy\"" ; do sleep "${POLLING_INTERVAL}"; done'

    - name: Debug HEALTHCHECK

      if: fromJSON(inputs.debug) && failure()

      env:
        NAME_OR_ID: ${{ inputs.container }}

      shell: bash

      run: |
         docker inspect --format "{{json .State.Health}}" "${NAME_OR_ID}" | jq
