name: compose-container
description: >
  Grabs the container of a given docker compose service.

inputs:

  compose-file:
    required: true

  service:
    required: true

outputs:

  id:
    description: >
      The input service's container id.
    value: ${{ steps.fetch.outputs.id }}

runs:

  using: composite

  steps:

    - name: Retrieve service container id

      id: fetch

      env:
        COMPOSE_FILE: ${{ inputs.compose-file }}
        SERVICE: ${{ inputs.service }}

      shell: bash

      run: |
        CONTAINER_ID="$(docker compose --env-file '.env' --file "${COMPOSE_FILE}" ps -aq "${SERVICE}")"
        echo "id=${CONTAINER_ID}" >> "$GITHUB_OUTPUT"
        test -n "${CONTAINER_ID}"
