name: Install
description: Installs Meteor and npm dependencies
runs:
  using: composite
  steps:
    - name: Set $PATH 🪜
      run: echo "$HOME/.meteor" >> $GITHUB_PATH
      shell: bash

    - name: Set env.METEOR_RELEASE 📻
      run: echo "METEOR_RELEASE=$(cat .meteor/release | cut -d@ -f2)" >> $GITHUB_ENV
      shell: bash

    - name: Cache ~/.meteor (Meteor ${{ env.METEOR_RELEASE }}) 💿
      uses: actions/cache@v2
      id: cache-meteor
      env:
        cache-name: cache-meteor
      with:
        path: ~/.meteor
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.METEOR_RELEASE }}-${{ hashFiles('.meteor/release') }}-${{ hashFiles('.meteor/versions') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ env.METEOR_RELEASE }}-${{ hashFiles('.meteor/release') }}-
          ${{ runner.os }}-${{ env.cache-name }}-${{ env.METEOR_RELEASE }}-

    - name: Install Meteor ${{ env.METEOR_RELEASE }} ☄️
      if: steps.cache-meteor.outputs.cache-hit != 'true'
      run: curl https://install.meteor.com?release=${{ env.METEOR_RELEASE }} | sh
      shell: bash

    - name: Cache ~/.npm 📀
      uses: actions/cache@v2
      env:
        cache-name: cache-npm
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-
          ${{ runner.os }}-

    - name: Cache ./node_modules 💽
      uses: actions/cache@v2
      id: cache-node-modules
      env:
        cache-name: cache-node-modules
      with:
        path: ./node_modules
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies 📦
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: meteor npm clean-install
      shell: bash

    - name: Cache ./.meteor/local 💾
      uses: actions/cache@v2
      env:
        cache-name: cache-meteor-local
      with:
        path: |
          ./.meteor/local/resolver-result-cache.json
          ./.meteor/local/plugin-cache
          ./.meteor/local/isopacks
          ./.meteor/local/bundler-cache/scanner
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.METEOR_RELEASE }}-${{ hashFiles('.meteor/release') }}-${{ hashFiles('.meteor/versions') }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ env.METEOR_RELEASE }}-${{ hashFiles('.meteor/release') }}-${{ hashFiles('.meteor/versions') }}-${{ github.ref }}-
          ${{ runner.os }}-${{ env.cache-name }}-${{ env.METEOR_RELEASE }}-${{ hashFiles('.meteor/release') }}-${{ hashFiles('.meteor/versions') }}-
          ${{ runner.os }}-${{ env.cache-name }}-${{ env.METEOR_RELEASE }}-${{ hashFiles('.meteor/release') }}-
          ${{ runner.os }}-${{ env.cache-name }}-${{ env.METEOR_RELEASE }}-
