services:
  patient-db-backup-retention-policy:
    build:
      context: .
      dockerfile: .deploy/backup-retention-policy/Dockerfile
    volumes:
      - ${BACKUP_DIR?error}:/backups
    environment:
      - BACKUP_RETENTION_POLICY_SCHEDULE=${BACKUP_RETENTION_POLICY_SCHEDULE?error}
      - BACKUP_RETENTION_POLICY_INTERVAL=${BACKUP_RETENTION_POLICY_INTERVAL?error}
    networks:
      - patient-backup-retention-policy-network

networks:
  patient-backup-retention-policy-network:
