name: ci:build

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  build:
    name: Continuous integration (build)
    strategy:
      matrix:
        platform:
          - ubuntu-latest
        architecture:
          - os.linux.x86_64

    runs-on: ${{ matrix.platform }}

    timeout-minutes: 15

    outputs:
      node-version: ${{ steps.meteor-node.outputs.version }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install 💾
        uses: meteor-actions/install@v3

      - name: Get Meteor's Node version
        id: meteor-node
        run: |
          echo \
          "version=$(meteor node --version | tail -c +2)" \
          >> "$GITHUB_OUTPUT"

      - name: Cache build 💽
        uses: meteor-actions/cache-build@v3
        with:
          key: build

      - name: Build 🏗️
        run: meteor npm run build -- ./dist --architecture ${{ matrix.architecture }}

      - name: Archive build 💽
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          retention-days: 1


  test:
    needs:
      - build

    strategy:
      matrix:
        platform:
          - ubuntu-latest

    runs-on: ${{ matrix.platform }}

    timeout-minutes: 1

    steps:
      - name: Load build 💽
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ needs.build.outputs.node-version }}

      - name: Node WIP
        run: node --version

      - name: Dist WIP
        run: ls -la dist
