name: ci:build:image:backup

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/patient-backup

jobs:

  build:
    name: Continuous integration (build image backup)
    strategy:
      matrix:
        platform:
          - ubuntu-latest

    runs-on: ${{ matrix.platform }}

    timeout-minutes: 15

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Log in to GitHub Packages registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and publish
        uses: ./.github/actions/package/build-publish
        with:
          file: .deploy/backup/Dockerfile
          package: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
