name: ci:lint-config

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  lint:
    name: Continuous integration (lint config)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Install 💾
        uses: ./.github/actions/install

      - name: Lint config 👕
        run: meteor npm run lint-config
