name: ci:type-check

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  type-check:
    name: Continuous integration (type check)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6

      - name: Install 💾
        uses: ./.github/actions/install

      - name: TypeScript check ☑️
        run: meteor npm run tsc
